### ISSUE TITLE
Horrible Bug

### ISSUE THREAD

**Issue by ItzNotABug** [realchandan/appopenads#2]
Hi,
Could you pl. let me know what `horrible bug` did you fix, so that I can also reflect the same in the repo that you've forked from.
I could only see the the removal of `adUnitId` which had a default of Test Ad Unit Id for debugging & testing.

Thanks.

**Comment by realchandan** [comment]
bro, your library is Apache v2.0 which let's me do whatever the hell I want. What is your problem then?

**Comment by ItzNotABug** [comment]
Did I ever say that I had any "problem" with whatever the hell you did?
No!
I saw a commit & it's message & it got me thinking if there's something wrong in my code which I wasn't able to find relating to your commit, & therefore I just "asked".

That's all.
Have some respect towards others though.

**Comment by realchandan** [comment]
Okay, bro, I didnot mention you in README.md I am sorry, I will write that It all was your code except the Java code.

**Comment by realchandan** [comment]
But I added the screenshots for people to get a feel of what the library is! and made it available through jitpack before you.

**Comment by ItzNotABug** [comment]
Never said anything on that part bro.
My concern was only and only towards the "Fixed a Horrible Bug" comment, which led me to doubt my code for a moment, that's all. 

Have a good day! :)
